name := "cloud-hypervisor"
packages := "
cloud-hypervisor
edk2-cloud-hypervisor
rust-hypervisor-firmware-bin
"
external_repos := "https://download.opensuse.org/repositories/home:cloud-hypervisor/Fedora_41/home:cloud-hypervisor.repo"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default

version:
    #!/bin/bash
    set -euo pipefail
    # set -x
    rpm -qp --queryformat '%{VERSION}-%{RELEASE}' rpms/cloud-hypervisor-*.rpm > ./version
