name := "1password-cli"
packages := "1password-cli"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64
"

import '../sysext.just'

all: default

download-manual arch=arch:
    #!/bin/bash
    set -euo pipefail
    # set -x

    mkdir -p rpms
    curl -Lo rpms/1password-cli.rpm \
        https://downloads.1password.com/linux/rpm/stable/x86_64/1password-cli-latest.x86_64.rpm

version:
    rpm -qp --queryformat '%{VERSION}-%{RELEASE}' rpms/1password-cli-*.rpm > ./version
