name := "1password-cli"
packages := "1password-cli"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64
"
pre_commands := "rpm --import https://downloads.1password.com/linux/keys/1password.asc; echo -e '[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc' > /etc/yum.repos.d/1password.repo"

import '../sysext.just'

all: default

version:
    rpm -qp --queryformat '%{VERSION}-%{RELEASE}' rpms/1password-cli-latest.x86_64.rpm > ./version
