kube_version := "1.32"

name := "kubernetes-" + kube_version
packages := "
cri-tools"  + kube_version + "
kubernetes" + kube_version + "
kubernetes" + kube_version + "-client
kubernetes" + kube_version + "-kubeadm
"
exclude_packages := "
cri-tools
"
upholds := "
kubelet.service
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
quay.io/fedora/fedora-coreos:next x86_64,aarch64
"

import '../sysext.just'

all: default

version:
    #!/bin/bash
    set -euo pipefail
    # set -x
    rpm -qp --queryformat '%{VERSION}-%{RELEASE}' rpms/kubernetes{{kube_version}}-{{kube_version}}*.rpm > ./version

# Setup folder that is expected by Kubernetes
install-manual:
    #!/bin/bash
    set -euo pipefail
    # set -x
    if [[ "${UID}" == "0" ]]; then
        SUDO=""
    else
        SUDO="sudo"
    fi
    cd rootfs
    ${SUDO} install -d -m 755 -o 0 -g 0 usr/libexec/kubernetes/kubelet-plugins/volume/exec
