name: "Publish 'latest' release with all sysexts"
description: "Publish the 'latest' release that references all available sysexts"

# This composite action needs the ARCH & RELEASEURL environment variables to be
# set at the workflow level

runs:
  using: "composite"
  steps:
    - name: "Publish 'latest-$ARCH' release"
      env:
        GH_TOKEN: ${{ github.token }}
      if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
      shell: bash
      run: |
        set -euxo pipefail

        rm -f SHA256SUMS*

        LATEST="-latest-${ARCH}"
        TAGNAME="latest-${ARCH}"
        releases=(
          $(
            gh release list --limit 1000 --json tagName \
              | jq --arg LATEST "${LATEST}" --arg TAGNAME "${TAGNAME}" --raw-output '
                map(
                  select(
                    (.tagName | endswith($LATEST))
                    and
                    (.tagName != $TAGNAME)
                  )
                )
                | .[].tagName
              ' \
              | sort -h
          )
        )
        echo "Looking at releases: ${releases[@]}"
        for rel in ${releases[@]}; do
          echo "Fetching SHA256SUMS for release: ${rel}"
          curl --location --output "SHA256SUMS.${rel}" "${RELEASEURL}/${rel}/SHA256SUMS"
        done
        ls ./SHA256SUMS.* | sort -h | xargs cat > SHA256SUMS
        new="$(cat SHA256SUMS | sha256sum)"

        old=""
        release="$(
          gh release list --limit 1000 --json tagName \
            | jq --arg TAGNAME "${TAGNAME}" --raw-output '
                map(
                  select(.tagName == $TAGNAME)
                )
                | .[].tagName
              '
        )"
        if [[ -n "${release}" ]]; then
          echo "Fetching SHA256SUMS from existing release: ${TAGNAME}"
          curl --location --output SHA256SUMS.old "${RELEASEURL}/${TAGNAME}/SHA256SUMS"
          old="$(cat SHA256SUMS.old | sha256sum)"
        fi

        if [[ "${new}" == "${old}" ]]; then
          echo "No changes for ${TAGNAME} since last release. Skipping."
        else
          echo "Creating new release: ${TAGNAME}"

          for rel in ${releases[@]}; do
            s="${rel%-latest-${ARCH}}"
            sed "s/%%SYSEXT%%/${s}/g" .workflow-templates/systemd-sysupdate.conf > ${s}.conf
          done

          {
          echo "Releases available:"
          echo "\`\`\`"
          cat ./SHA256SUMS
          echo "\`\`\`"
          } > notes

          gh release delete \
            --cleanup-tag \
            --yes \
            "${TAGNAME}" \
            || true

          gh release create \
            --title "System extensions for Fedora (${ARCH})" \
            --notes-file notes \
            "${TAGNAME}" \
            --latest=true \
            ./SHA256SUMS ./*.conf
        fi
