name := "steam-devices"
packages := "steam-devices"
enable_repos := "rpmfusion-nonfree-steam"
dnf_arch := "i686"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default
