name := "mpd"
packages := "
mpd
mpc
mpdris2
ncmpcpp
"
rpm_fusion_repos := "free nonfree"
base_images := "
"
# quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
# quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64

import '../sysext.just'

all: default
