name := "incus"
packages := "
incus
incus-client
"
copr_repos := "ganto/lxc4"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
"

import '../sysext.just'

all: default

version:
    rpm -qp --queryformat '%{VERSION}-%{RELEASE}' rpms/incus-client-*.rpm > ./version
