name: "Build sysexts: Fedora CoreOS (stable, x86_64)"

env:
  IMAGE: 'quay.io/fedora/fedora-coreos:stable'
  RELEASE: 'stable'
  NAME: 'Fedora CoreOS'
  SHORTNAME: 'fedora-coreos'
  GH_TOKEN: ${{ github.token }}
  PR: ${{ github.event_name == 'pull_request' }}
  ARCH: 'x86_64'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.sysext }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: "ubuntu-24.04"
    container:
      image: "quay.io/fedora/fedora:41"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: "Install tools"
        run: |
          dnf install -y \
            cpio \
            dnf5-plugins \
            erofs-utils \
            git \
            jq \
            just \
            podman \
            wget
          dnf config-manager addrepo --from-repofile="https://cli.github.com/packages/rpm/gh-cli.repo"
          dnf install -y gh --repo gh-cli

      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: cilium-cli"
        env:
          SYSEXT: cilium-cli
        run: |
          cd "${SYSEXT}"
          if [[ "${PR}" == "true" ]]; then
              diff="$(git diff origin/main HEAD --stat -- . ; git diff origin/main HEAD --stat -- ../sysext.just)"
              if [[ -z "${diff}" ]]; then
                  echo "Skipping: No changes for this sysext in this PR"
                  exit 0
              fi
          fi
          just build ${IMAGE} ${ARCH}

      - name: "Publish sysext: cilium-cli"
        env:
          SYSEXT: cilium-cli
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          git config --global --add safe.directory "${PWD}"

          cd "${SYSEXT}"
          sha256sum *.raw > SHA256SUMS

          arch=""
          if [[ "${ARCH}" == "x86_64" ]]; then
              arch="x86-64"
          else
              arch="aarch64"
          fi

          # FIXME
          VERSION_ID="41"
          VERSION="$(cat ./version)"

          {
          echo "Built using container image \`${IMAGE}\` with digest:"
          echo "\`\`\`"
          cat ./digest
          echo "\`\`\`"

          if [[ -f ./rpms ]]; then
            echo ""
            echo "Built using RPMs:"
            echo "\`\`\`"
            cat ./rpms
            echo "\`\`\`"
          fi

          if [[ -f ./inputs ]]; then
            echo ""
            echo "Built using input files:"
            echo "\`\`\`"
            cat ./inputs
            echo "\`\`\`"
          fi
          } > notes

          gh release delete \
            --cleanup-tag \
            --yes \
            "${SYSEXT}-${VERSION_ID}-${VERSION}-${arch}" \
            || true

          gh release create \
            --title "${SYSEXT} ${VERSION} for Fedora ${VERSION_ID} (${ARCH})" \
            --notes-file notes \
            "${SYSEXT}-${VERSION_ID}-${VERSION}-${arch}" \
            --latest=false \
            ./*.raw ./SHA256SUMS
