name: "Build sysexts: Fedora CoreOS (stable, x86_64)"

env:
  IMAGE: 'quay.io/fedora/fedora-coreos:stable'
  GH_TOKEN: ${{ github.token }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * MON'
  workflow_dispatch:

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.sysext }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/travier/fedora-sysexts-exp/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: cilium-cli"
        uses: ./.github/actions/build
        with:
          sysext: 'cilium-cli'
          image: ${{ env.IMAGE }}

  build-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/travier/fedora-sysexts-exp/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Setup artifacts and dnf cache directories"
        run: |
          mkdir -p artifacts .dnf-cache

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysext: cilium-cli"
        uses: ./.github/actions/build
        with:
          sysext: 'cilium-cli'
          image: ${{ env.IMAGE }}

  publish-sysext-latest:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/travier/fedora-sysexts-exp/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    # Run after the builds and versionned release
    needs:
      - build-x86_64
      - build-aarch64
    # Still run if any dependent job fails
    # if: ${{ always() }}
    if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Gather versions for sysext: cilium-cli"
        uses: ./.github/actions/gather
        with:
          sysext: 'cilium-cli'

  publish-latest:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/travier/fedora-sysexts-exp/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    # Run after the all sysext-latest releases
    needs:
      - publish-sysext-latest
    # Still run if any dependent job fails
    # if: ${{ always() }}
    if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Update latest release for all sysexts"
        uses: ./.github/actions/latest
